# Dan's solution:

In [50]:
import numpy as np
import random
keyboard = np.array([[1,2,3],[4,5,6],[7,8,9]])
board = np.chararray((3,3))
moves_dict = {1:(0,0), 2:(0,1), 3:(0,2), 4:(1,0), 5:(1,1), 6:(1,2), 7:(2,0), 8:(2,1), 9:(2,2)}
wincombos = [board[0], board[1], board[2], board[:,0], board[:,1], board[:,2], board.diagonal(), np.fliplr(board).diagonal()]

def check_win(board):
    global endgame
    global win
    global lose
    
    for w in wincombos:
        w = list(w)
        if w.count('O') == 3:
            endgame = True
            lose = True
        
        if w.count('X') == 3:
            endgame = True
            win = True
    

def make_computer_move(board):
    '''Only makes random moves. 
    
    If you want to improve the game's AI, start here.
    '''
    #Make a random move 
    testx = random.randint(0,2)
    testy = random.randint(0,2)
    
    #Check if that space is occupied
    while board[testx][testy] != '-':
        testx = random.randint(0,2)
        testy = random.randint(0,2)

    x = testx
    y = testy 
    board[x][y] = 'O'
            
    return board

def make_player_move(board):
    move = int(input('Please enter your move (1-9): '))
    
    #Check if the input is valid
    if move < 1 or move > 9:
        while move < 1 or move > 9:
            move = int(input('That is an invalid move. Please re-enter your move: '))

    move_x, move_y = moves_dict[move]
    
    #Check if the space is taken
    while board[move_x][move_y] != '-':
        move = int(input('That is an invalid move. Please re-enter your move: '))
        move_x, move_y = moves_dict[move]

    board[move_x][move_y] = 'X'

    return board

def play_game():
    board[:] = '-'
    global endgame
    global win 
    global lose

    print keyboard
    print board

    while not endgame:

        make_player_move(board)
        check_win(board)

        if '-' not in board:
            endgame = True
            break

        make_computer_move(board)
        check_win(board)

        print board

    if win:
        print "You win"
    elif lose:
        print "Computer wins"
    elif endgame:
        print "Tie game"
    


In [51]:
endgame = False
win = False
lose = False

play_game()


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[['-' '-' '-']
 ['-' '-' '-']
 ['-' '-' '-']]
Please enter your move (1-9): 2
[['O' 'X' '-']
 ['-' '-' '-']
 ['-' '-' '-']]
Please enter your move (1-9): 5
[['O' 'X' '-']
 ['-' 'X' 'O']
 ['-' '-' '-']]
Please enter your move (1-9): 8
[['O' 'X' '-']
 ['O' 'X' 'O']
 ['-' 'X' '-']]
You win


# NYC DSI 1 solutions:

# Lydia:

In [ ]:
import pandas as pd
df = pd.DataFrame(np.nan,index =[1,2,3], columns = [1,2,3])
while df.isnull().any().any() == True: 
    print 'Your Turn! '
    a = raw_input('which row: ')
    b = raw_input('which column: ')
    df.loc[int(a),int(b)] = 'X' 
    print df
    print ' '
    print 'Computer\'s Turn'
    
    while df.loc[int(ac),int(bc)] in ['X' , 'O']:
        ac = np.random.randint(1, 3)
        bc = np.random.randint(1, 3)
    else:
        df.loc[int(ac),int(bc)] = 'O' 
        print 'computer played: ' + str(ac) +' '+ str(bc)
    print df
    print '----'
    
    for x in df: 
        if (x.all() == 'X')== True:
            print 'Yay! You won!'
    print ' '
    
    if df.isnull().any().any() == False:
        print 'Oops. Tie!!'
        df = pd.DataFrame()
        df = pd.DataFrame(np.nan,index =[1,2,3], columns = [1,2,3])
        break 

# Tucker and Tim

In [ ]:
A,B,C,D,E,F,G,H,I = 0,0,0,0,0,0,0,0,0
moves = [A,B,C,D,E,F,G,H,I]
wins = [[A,B,C],[D,E,F],[G,H,I],[A,D,G],[B,E,H],[C,F,I],[A,E,I],[C,E,G]]
wins2 = [['A','B','C'],['D','E','F'],['G','H','I'],['A','D','G'],['B','E','H'],['C','F','I'],['A','E','I'],['C','E','G']]


def computermove(wins,wins2):
    if E == 0: return "E"
    for i in wins:
        available = []
        if 2 not in i:
            available.append(i)
    for i in available:
        b = 0
        if sum(i) > b: 
            b = sum(i)
            line = i
    for i in available(line):
        if i == 0:
            return wins2[line][i]

computermove(wins,wins2)

def move (player):
    if player == 1: 
        XO = "X"
    else: XO = "O"
  
    move = raw_input('select your move: ')
    if move == 'A' or move == 'a':
        moves[0] = XO
        A = player
        return 
    elif move == 'B' or move == 'b':
        moves[1] = XO
        B = player
    elif move == 'C' or move == 'c':
        moves[2] = XO
        C = player
    elif move == 'D' or move == 'd':
        moves[3] = XO
        D = player
    elif move == 'E' or move == 'e':
        moves[4] = XO
        E = player
    elif move == 'F' or move == 'f':
        moves[5] = XO
        F = player
    elif move == 'G' or move == 'g':
        moves[6] = XO
        G = player
    elif move == 'H' or move == 'h':
        moves[7] = XO
        H = player
    elif move == 'I' or move == 'i':
        moves[8] = XO
        I = player
    else: return 'please select a real move'
       

print '''
    A|B|C
   -------
    D|E|F
   -------
    H|I|J'''

def board():
    print "\n\t",moves[0],"|",moves[1],"|",moves[2]
    print "\t", "--------"
    print "\n\t",moves[3],"|",moves[4],"|",moves[5]
    print "\t", "--------"
    print "\n\t",moves[6],"|",moves[7],"|",moves[8], "\n"
    
def game_engine():
    game_finished = True
    while game_finished == False:
        move()
        


board()
move()

# Rebecca:

In [ ]:
from random import randint

#initializing board
board = []

for x in range(3):
    board.append(['_'] * 3)

def print_board(board):
    for row in board:
        print ' '.join(row)
        
#starting the game and printing the board
print "Let's play TicTacToe!\n"
print_board(board)


#ask user for a guess
for turn in range(100):
    chosen_row = int(raw_input("\npick a row: "))
    chosen_col = int(raw_input("pick a column: "))
    print '\n'

    if board[chosen_row][chosen_col] != "_":
        print "Uh oh, that space is taken!  Please choose again.\n"
        
    elif (chosen_row < 0 or chosen_row > 2) or (chosen_col < 0 or chosen_col > 2):
        print "\nWhere'd you go??  That's not on the board!  Pick again.\n"
        
    else:
        board[chosen_row][chosen_col] = 'X'
        
    if (board[0][0] == board[0][1] == board[0][2] == 'X') or (board[1][0] == board[1][1] == board[1][2] == 'X') or\
        (board[2][0] == board[2][1] == board[2][2] == 'X') or (board[0][1] == board[1][1] == board[2][1] == 'X') or\
        (board[0][0] == board[1][0] == board[2][0] == 'X') or (board[0][2] == board[1][2] == board[2][2] == 'X') or\
        (board[0][0] == board[1][1] == board[2][2] == 'X') or (board[0][2] == board[1][1] == board[2][0] == 'X'):
        print_board(board)
        print "\nYou won!!!  Great job.\n"
        break
        
    #computy makes a move
    else: 
        checker = False
        while checker == False:
            checker = True
            def random_row(board):
                return randint(0, len(board) - 1)

            def random_col(board):
                return randint(0, len(board[0]) - 1)

            computer_row = random_row(board)
            computer_col = random_col(board)
            if board[computer_row][computer_col] in ['O', 'X']:
                checker = False
        board[computer_row][computer_col] = 'O'
    
        if (board[0][0] == board[0][1] == board[0][2] == 'O') or (board[1][0] == board[1][1] == board[1][2] == 'O') or\
            (board[2][0] == board[2][1] == board[2][2] == 'O') or (board[0][1] == board[1][1] == board[2][1] == 'O') or\
            (board[0][0] == board[1][0] == board[2][0] == 'O') or (board[0][2] == board[1][2] == board[2][2] == 'O') or\
            (board[0][0] == board[1][1] == board[2][2] == 'O') or (board[0][2] == board[1][1] == board[2][0] == 'O'):
            print_board(board)
            print "\nYou lost, sorry.  It happens.\n"
            break

    #is it a tie?    
    count = 0    
    for i in range(0,2):
        for j in range(0,2):
            if board[i][j] == '_':
                count += 1
    if count == 0:
        print_board(board)
        print '\nIt\'s a tie!  Nice job, everyone.'
        break
        
    else:
        print 'Nice job.'
        print_board(board)

# Hudson

In [ ]:
import random
import itertools

unclaimed_spaces = [1,2,3,4,5,6,7,8,9]

def winner(lista, listb):
    win_combos = [[1,4,7], [2,5,8], [3,6,9], [1,2,3], [4,5,6], [7,8,9], [1,5,9], [7,5,3]]
    if len(lista)>=3:
        for i in win_combos:
            for h in itertools.permutations(i,3):
                if h[0] in lista:
                    if h[1] in lista:
                        if h[2] in lista:
                            return(lista)
                        else:
                            continue
                    else:
                        continue
                else:
                    continue
                if h[0] in listb:
                    if h[1] in listb:
                        if h[2] in listb:
                            return(listb)
                        else:
                            continue
                    else:
                        continue
                else:
                    continue
        return 0


def pick_tic(unclaimed_spaces):
    lista = []
    listb = []
    while len(unclaimed_spaces)> 0:#while (len(lista)+len(listb)) < 9:
        if len(lista) <= len(listb): #this is because if player b enters the wrong thing, player a can pick twice
            picka = raw_input("Please select a number 1-9, corresponding to a 3x3 tic tac toe board. (1 is top left, 5 is middle, 9 is bottom right)")
            picka = int(picka)
            if picka in unclaimed_spaces:
                lista.append(picka)
                unclaimed_spaces.remove(picka)
                print("The remaining spaces are:", unclaimed_spaces, "Player A has selected:", lista, "Player B has selected:", listb)
                if winner(lista, listb) == lista:
                    print("Player A Wins! Victory!")
                elif winner(lista, listb) == listb:
                    print("Player B Wins! Victory!")
                pickb = raw_input("Please select a number 1-9, corresponding to a 3x3 tic tac toe board. (1 is top left, 5 is middle, 9 is bottom right)")
                pickb = int(pickb)
                if pickb in unclaimed_spaces:
                    listb.append(pickb)
                    unclaimed_spaces.remove(pickb)
                    print("The remaining spaces are:", unclaimed_spaces, "Player A has selected:", lista, "Player B has selected:", listb)
                    if winner(lista, listb) == lista:
                        print("Player A Wins! Victory!")
                        break
                    elif winner(lista, listb) == listb:
                        print("Player B Wins! Victory!")
                else:
                    print("That number is not available - or you picked something that does not make sense.")
                    continue
            else:
                print("That number is not available - or you picked something that does not make sense.")
                continue
        elif len(lista) > len(listb):
            pickb = raw_input("Please select a number 1-9, corresponding to a 3x3 tic tac toe board. (1 is top left, 5 is middle, 9 is bottom right)")
            pickb = int(pickb)
            if pickb in unclaimed_spaces:
                listb.append(pickb)
                unclaimed_spaces.remove(pickb)
                print("The remaining spaces are:", unclaimed_spaces, "Player A has selected:", lista, "Player B has selected:", listb)
                if winner(lista, listb) == lista:
                    print("Player A Wins! Victory!")
                elif winner(lista, listb) == listb:
                    print("Player B Wins! Victory!")
    return("Its a tie! Nobody won. Play again!")


pick_tic(unclaimed_spaces)
