# Tic Tac Toe

In [2]:
import random
import numpy as np

class tictactoe():
    def __init__(self):
        self.board = np.chararray((3,3))
        
        self.wincombos = [self.board[0], self.board[1], self.board[2], \
                          self.board[:,0], self.board[:,1], self.board[:,2], \
                          self.board.diagonal(), np.fliplr(self.board).diagonal()]
      
    keyboard = np.array([[1,2,3],[4,5,6],[7,8,9]])
    
    moves_dict = {1:(0,0), 2:(0,1), 3:(0,2), 4:(1,0), 5:(1,1), 6:(1,2), 7:(2,0), 8:(2,1), 9:(2,2)}
       
    
    def make_player_move(self):
        '''Takes an 1-9 input, maps the move to that place on the board'''
        move = int(input("Pick a space (1-9)"))
        
        if move < 1 or move > 9:
            while move < 1 or move > 9:
                move = int(input('That is an invalid move. Please re-enter your move: '))
                
        x, y = tictactoe.moves_dict[move]
        
        #Check if the space is taken
        while self.board[x][y] != '-':
            move = int(input('That is an invalid move. Please re-enter your move: '))
            x, y = tictactoe.moves_dict[move]
            
        self.board[x][y] = 'X'
        
        
    def make_computer_move(self):
        '''Only makes random moves. 

        If you want to improve the game's AI, start here.
        '''
        
        #Make a random move 
        x = random.randint(0,2)
        y = random.randint(0,2)

        #Check if that space is occupied
        while self.board[x][y] != '-':
            x = random.randint(0,2)
            y = random.randint(0,2)
            
        self.board[x][y] = 'O'
        
        
    def check_win(self):
        '''Checks the 3 rows, 3 columns and 2 diagonals for 3 Xs or 3 Os'''
        for w in self.wincombos:
            w = list(w)
            if w.count('O') == 3:
                self.endgame = True
                self.lose = True

            if w.count('X') == 3:
                self.endgame = True
                self.win = True
                                
    def check_over(self):
        '''Checks if there are any blank spaces left'''
        if '-' not in self.board:
            self.endgame = True
                
    def play_again(self):
        '''Runs play() again if the user asks for it'''
        again = str(raw_input("Would you like to play again? (Y/n)"))
        if 'y' in again.lower():
            print
            self.play()
    
    def play(self):
        '''Starts a new game
        As long as self.endgame is set to false, the player and
        computer will trade moves. 
        
        After each move, the computer checks for a win and a tie
        '''
        
        #Initialize the play variables for this method
        self.endgame = False
        self.win = False
        self.lose = False
        self.board[:] = '-'
        
        #Print the board
        print tictactoe.keyboard
        print self.board
        
        
        while not self.endgame:
            self.make_player_move()
            self.check_win()
            self.check_over()
            print self.board
                            
            if not self.endgame:
                self.make_computer_move()
                self.check_win()
                print 
                print "Computer moved:"
                print self.board

        if self.win:
            print "You win"
        elif self.lose:
            print "Computer wins"
        elif self.endgame:
            print "Tie game"
        
        self.play_again()
        
        


In [3]:
go = tictactoe()
go.play()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[['-' '-' '-']
 ['-' '-' '-']
 ['-' '-' '-']]
Pick a space (1-9)1
[['X' '-' '-']
 ['-' '-' '-']
 ['-' '-' '-']]

Computer moved:
[['X' '-' '-']
 ['-' '-' 'O']
 ['-' '-' '-']]
Pick a space (1-9)2
[['X' 'X' '-']
 ['-' '-' 'O']
 ['-' '-' '-']]

Computer moved:
[['X' 'X' 'O']
 ['-' '-' 'O']
 ['-' '-' '-']]
Pick a space (1-9)3
That is an invalid move. Please re-enter your move: 4
[['X' 'X' 'O']
 ['X' '-' 'O']
 ['-' '-' '-']]

Computer moved:
[['X' 'X' 'O']
 ['X' '-' 'O']
 ['-' '-' 'O']]
Computer wins
Would you like to play again? (Y/n)n


In [4]:
class smart_game(tictactoe):
    
    def take_center(self):
        self.board[1][1] = 'O'
        
        
    def make_computer_move(self):
        if self.board[1][1] == '-':
            self.take_center()
            
        else:
            #Make a random move 
            x = random.randint(0,2)
            y = random.randint(0,2)

            #Check if that space is occupied
            while self.board[x][y] != '-':
                x = random.randint(0,2)
                y = random.randint(0,2)

            self.board[x][y] = 'O'
        

In [5]:
smart_tictac = smart_game()
smart_tictac.play()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[['-' '-' '-']
 ['-' '-' '-']
 ['-' '-' '-']]
Pick a space (1-9)1
[['X' '-' '-']
 ['-' '-' '-']
 ['-' '-' '-']]

Computer moved:
[['X' '-' '-']
 ['-' 'O' '-']
 ['-' '-' '-']]
Pick a space (1-9)2
[['X' 'X' '-']
 ['-' 'O' '-']
 ['-' '-' '-']]

Computer moved:
[['X' 'X' '-']
 ['-' 'O' '-']
 ['-' '-' 'O']]
Pick a space (1-9)4
[['X' 'X' '-']
 ['X' 'O' '-']
 ['-' '-' 'O']]

Computer moved:
[['X' 'X' '-']
 ['X' 'O' 'O']
 ['-' '-' 'O']]
Pick a space (1-9)8
[['X' 'X' '-']
 ['X' 'O' 'O']
 ['-' 'X' 'O']]

Computer moved:
[['X' 'X' 'O']
 ['X' 'O' 'O']
 ['-' 'X' 'O']]
Computer wins
Would you like to play again? (Y/n)n


# War

In [6]:
class Card():
    '''A standard playing card'''
    
    def __init__(self, suit=0, rank=2):
        self.suit = suit
        self.rank = rank
        
    suit_names = ['Clubs', 'Diamonds', 'Hearts', 'Spades']
    rank_names = [None, 'Ace', '2', '3', '4', '5', '6', '7', '8', \
                 '9', '10', 'Jack', 'Queen', 'King']
    
    def __str__(self):
        return "%s of %s" % (Card.rank_names[self.rank], \
                            Card.suit_names[self.suit])
    
    def greater_than(self, other):
        if isinstance(other, Card):
            return self.rank > other.rank

In [7]:
class Deck():
    '''52 unique cards. No jokers.'''
    
    def __init__(self):
        self.cards = []
        for suit in range(4):
            for rank in range(1,14):
                card = Card(suit, rank)
                self.cards.append(card)
                
    def __str__(self):
        results = []
        for card in self.cards:
            results.append(str(card))
        return '\n'.join(results)
    
    def draw_card(self):
        '''Draws a random card'''
        import random
        c = random.choice(self.cards)
        self.cards.remove(c)
        return c
    
    def add_card(self, card):
        '''Puts a card object back in the deck'''
        self.cards.append(card)            
    
    def shuffle(self):
        '''Shuffles the deck'''
        import random
        random.shuffle(self.cards)
        
    def sort(self):
        '''Sorts the deck'''
        self.cards.sort()

In [8]:
class Hand(Deck):
    '''Empty for now'''
    def __init__(self):
        self.cards = []

In [9]:
class War():
    def __init__(self):
        self.deck = Deck()
        self.player1 = Hand()
        self.player2 = Hand()

        self.player1_win_pile = []
        self.player2_win_pile = []

    def deal(self):
        '''Deal half the deck to each player'''
        for i in range(26):
            card = self.deck.draw_card()
            self.player1.add_card(card)

            card = self.deck.draw_card()
            self.player2.add_card(card)

    def turn(self):
        '''Each player plays a card. The highest card takes the pile'''
        card1 = self.player1.draw_card()
        card2 = self.player2.draw_card()

        print "Player 1 played:"
        print card1
        print "Player 2 played:"
        print card2

        if card1.greater_than(card2):
            print "Player 1 wins the hand"
            print
            self.player1_win_pile.append(card1)
            self.player1_win_pile.append(card2)
        else:
            print "Player 2 wins the hand"
            print
            self.player2_win_pile.append(card1)
            self.player2_win_pile.append(card2)

    def auto_play(self):
        while len(self.player1.cards) > 0:
            self.turn()

        if len(self.player1_win_pile) > len(self.player2_win_pile):
            print "************"
            print "PLAYER 1 WINS"
            print "%i cards" % len(self.player1_win_pile)
            print "************"
        else:
            print "************"
            print "PLAYER 2 WINS"
            print "%i cards" % len(self.player2_win_pile)
            print "************"

In [10]:
war_game = War()
war_game.deal()
war_game.auto_play()

Player 1 played:
Jack of Spades
Player 2 played:
Jack of Hearts
Player 2 wins the hand

Player 1 played:
8 of Diamonds
Player 2 played:
King of Spades
Player 2 wins the hand

Player 1 played:
5 of Hearts
Player 2 played:
Queen of Diamonds
Player 2 wins the hand

Player 1 played:
6 of Spades
Player 2 played:
8 of Hearts
Player 2 wins the hand

Player 1 played:
King of Diamonds
Player 2 played:
7 of Clubs
Player 1 wins the hand

Player 1 played:
9 of Spades
Player 2 played:
King of Clubs
Player 2 wins the hand

Player 1 played:
Queen of Spades
Player 2 played:
8 of Clubs
Player 1 wins the hand

Player 1 played:
10 of Clubs
Player 2 played:
Ace of Diamonds
Player 1 wins the hand

Player 1 played:
5 of Clubs
Player 2 played:
9 of Diamonds
Player 2 wins the hand

Player 1 played:
7 of Spades
Player 2 played:
Jack of Diamonds
Player 2 wins the hand

Player 1 played:
9 of Clubs
Player 2 played:
7 of Hearts
Player 1 wins the hand

Player 1 played:
3 of Clubs
Player 2 played:
Jack of Clubs
Play