In [2]:
from __future__ import print_function, division

import random
import numpy as np
import pandas as pd
import scipy

In [3]:
# Generate some random numbers

num_list = [random.randint(0,1000) for i in range(100000)]
num_arr = np.array(num_list)
num_series = pd.Series(num_list)

# Sum Operations

## For loop

In [4]:
%%timeit

# Standard for loop accumulation
total = 0
for n in num_list:
    total += n

100 loops, best of 3: 4.95 ms per loop


## Reduce

In [5]:
%%timeit
reduce(lambda x, y: x+y, num_list)

100 loops, best of 3: 10.6 ms per loop


## Standard library sum

In [6]:
%%timeit
sum(num_list)

1000 loops, best of 3: 723 µs per loop


## Numpy sum (Vectorized)

In [7]:
%%timeit
num_arr.sum()

The slowest run took 5.69 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 50.6 µs per loop


## Why is NumPy so much faster than the Python standard library? 
> The ndarray object is of **fixed size** and **all elements are the same datatype**. This allows aggregations such as summing to be performed by *pre-compiled C code*. <br><br>The ndarray's sum method and the pandas Series' sum method are examples of vectorized operations, a standard component of array programming. 

# Array Dimensions & Shapes

## np.arange()

In [8]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [9]:
a = np.arange(6)

In [10]:
a

array([0, 1, 2, 3, 4, 5])

In [11]:
a.shape

(6,)

In [12]:
a.ndim

1

In [13]:
a32 = a.reshape(3,2)

In [14]:
a32

array([[0, 1],
       [2, 3],
       [4, 5]])

In [15]:
a32.shape

(3, 2)

In [16]:
a32.ndim

2

In [17]:
a23 = a.reshape(2,3)

In [18]:
a23

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
a23.shape

(2, 3)

In [20]:
a16 = a.reshape(1,6)

In [21]:
a16

array([[0, 1, 2, 3, 4, 5]])

In [22]:
a16.shape

(1, 6)

In [23]:
a16.ndim

2

In [28]:
a_neg1 = a.reshape(1,-1)

In [30]:
x = a_neg1.reshape(1,-1)

In [31]:
x

array([[0, 1, 2, 3, 4, 5]])

In [32]:
a_neg1.shape

(1, 6)

In [33]:
a_neg1.ndim

2

## Other useful numpy functions

In [34]:
a.min()

0

In [35]:
a.max()

5

In [36]:
a = a[::-1]

In [37]:
a

array([5, 4, 3, 2, 1, 0])

In [38]:
a.argmin()

5

In [39]:
a.argmax()

0

In [40]:
np.zeros(100)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [41]:
np.zeros_like(a)

array([0, 0, 0, 0, 0, 0])

In [43]:
np.ones_like([[23,3,4,4],[1,2,3,4]])

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])