In [19]:
# import numpy
import numpy as np 

# create array x
print 'Creating array x'
x = np.array([1, 2, 3, 4]) 
print ''
print 'x is: '
print x
print ''

Creating array x

x is: 
[1 2 3 4]



In [20]:
# print the shape of x
print 'The shape of x is: '
print x.shape 
print ''


The shape of x is: 
(4,)



In [21]:
# create a two dimensional array
print 'Creating two dimensional array x'
x = np.array([[1, 2, 3, 4],[4,5,6,2],[1,2,4,5]])
print ''
print 'x is :'
print x
print''

Creating two dimensional array x

x is :
[[1 2 3 4]
 [4 5 6 2]
 [1 2 4 5]]



In [22]:
# print shape of 2d array
print 'The shape of 2d array is :'
print x.shape
print ''

The shape of 2d array is :
(3, 4)



In [23]:
# reshape the array to 2 x 6
print 'Reshaping 2d array to 2,6'
x=np.reshape(x, (2, 6))
print 'New x is: '
print x
print ''

Reshaping 2d array to 2,6
New x is: 
[[1 2 3 4 4 5]
 [6 2 1 2 4 5]]



In [24]:
# reshape the array to 1 x 12
print 'Reshaping 2d array to 1, 12'
x=np.reshape(x, (1, 12)) 
print 'New x is :'
print x

Reshaping 2d array to 1, 12
New x is :
[[1 2 3 4 4 5 6 2 1 2 4 5]]


In [25]:
# transpose the array
print 'Tranpose of x is:' 
print x.T

Tranpose of x is:
[[1]
 [2]
 [3]
 [4]
 [4]
 [5]
 [6]
 [2]
 [1]
 [2]
 [4]
 [5]]


In [33]:
# indexing method 1
print 'Indexing method 1, the 5th value is: ' 
print x[0,4]

Indexing method 1, the 5th value is: 
4


In [27]:
# indexing method 2
print 'Indexing method 2, the 2nd to the last value is: '
print x[0,-2]

Indexing method 2, the 2nd to the last value is: 
4


In [28]:
# indexing method 3
print 'Indexing method 3, the 5th to the last value is:'
print x[0][-5]

Indexing method 3, the 5th to the last value is:
2


In [29]:
# indexing method 4
print 'Indexing method 4, the elements 2 to 5(starting from 0) are: '
print x[0,2:5]

Indexing method 4, the elements 2 to 5(starting from 0) are: 
[3 4 4]


In [31]:
# indexing method 5
print 'Indexing method 6, the elemetns 1, 2, 3, and 6 are: '
arr=np.array([1,2,3,6])
print x[0,arr]

Indexing method 6, the elemetns 1, 2, 3, and 6 are: 
[2 3 4 6]


In [32]:
# indexing method 6
print 'Indexing method 7, values in x > 4 are: '
print x[0,x[0,:]>4]

Indexing method 7, values in x > 4 are: 
[5 6 5]
